services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.32.0
    container_name: swagger-ui

    networks:
      - net
    environment:
      - CONFIG_URL=/swagger-ui/swagger-config.json
    volumes:
      - ./swagger-ui/config.json:/usr/share/nginx/html/swagger-config.json
