services:
  kong:
    image: kong:3.9.1
    container_name: gateway

    command: kong start

    networks:
      - net
    ports:
      - ${PUBLIC_BASE_PORT}:8000
      - ${API_GATEWAY_ADMIN_PORT}:8001

    volumes:
      - ./kong/kong.conf:/etc/kong/kong.conf
      - ./kong/kong.yml:/kong/kong.yml
      - ./kong/plugins:/kong/plugins:ro

  konga:
    image: pantsel/konga:latest
    container_name: gateway-admin

    networks:
      - net
    depends_on:
      - kong
    ports:
      - ${API_GATEWAY_UI_PORT}:1337

    environment:
      - NODE_ENV=development
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/app/seeds/user_seed.json
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/app/seeds/kong_node_seed.json
    volumes:
      - ./kong/konga/seeds:/app/seeds
      - konga-data:/data

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    container_name: oauth-gateway

    entrypoint: /entrypoint.sh

    networks:
      - net
    depends_on:
      - keycloak

    environment:
      - BROWSE_ACCESS_URL=http://${PUBLIC_BASE_DOMAIN}:${PUBLIC_BASE_PORT}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - OAUTH2_PROXY_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    volumes:
      - ./oauth2-proxy/config.cfg:/etc/oauth2-proxy/config.cfg
      - ./oauth2-proxy/entrypoint.sh:/entrypoint.sh

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: idP

    command:
      - start
      - --import-realm

    networks:
      - net

    environment:
      - KC_HOSTNAME=${PUBLIC_BASE_DOMAIN}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/realm-dev.json:/opt/keycloak/data/import/realm-dev.json
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf

volumes:
  konga-data:
    driver: local
