services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb

    networks:
      - net
    ports:
      - ${MONGODB_PORT}:27017

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - mongo-data:/data/db

    healthcheck:
      test: >
        mongosh --quiet
        -u ${MONGODB_USERNAME}
        -p ${MONGODB_PASSWORD}
        --authenticationDatabase admin
        --eval "db.adminCommand('ping').ok"

  dynamodb:
    image: amazon/dynamodb-local:3.1.0
    container_name: dynamodb

    command: >
      -jar DynamoDBLocal.jar
      -sharedDb
      -dbPath /home/dynamodblocal/data

    networks:
      - net
    ports:
      - ${DYNAMODB_PORT}:8000

    volumes:
      - dynamo-data:/home/dynamodblocal/data

    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kong:
    image: kong:3.9.1
    container_name: kong-container

    command: kong start

    networks:
      - net
    ports:
      - ${PUBLIC_BASE_PORT}:8000
      - ${API_GATEWAY_ADMIN_PORT}:8001

    volumes:
      - ./kong/kong.conf:/etc/kong/kong.conf
      - ./kong/kong.yml:/kong/kong.yml
      - ./kong/plugins:/kong/plugins:ro

  konga:
    image: pantsel/konga:latest
    container_name: konga-container

    networks:
      - net
    depends_on:
      - kong
    ports:
      - ${API_GATEWAY_UI_PORT}:1337

    environment:
      - NODE_ENV=development
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/app/seeds/user_seed.json
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/app/seeds/kong_node_seed.json
    volumes:
      - ./kong/konga/seeds:/app/seeds
      - konga-data:/data

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    container_name: auth-gateway

    entrypoint: /entrypoint.sh

    networks:
      - net
    depends_on:
      - keycloak

    environment:
      - BROWSE_ACCESS_URL=http://${PUBLIC_BASE_DOMAIN}:${PUBLIC_BASE_PORT}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - OAUTH2_PROXY_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    volumes:
      - ./oauth2-proxy/config.cfg:/etc/oauth2-proxy/config.cfg
      - ./oauth2-proxy/entrypoint.sh:/entrypoint.sh

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: identity-provider

    command:
      - start
      - --import-realm

    networks:
      - net

    environment:
      - KC_HOSTNAME=${PUBLIC_BASE_DOMAIN}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/realm-dev.json:/opt/keycloak/data/import/realm-dev.json
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf

volumes:
  mongo-data:
    driver: local
  dynamo-data:
    driver: local
  konga-data:
    driver: local
