spring:
  application:
    name: calendar

  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      auto-index-creation: false

mongock:
  migration-scan-package:
    - com.pickme.calendar.infrastructure.migration.mongock
  enabled: true

server:
  servlet:
    context-path: /calendar

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: ${INTERNAL_JWT_SECRET}
