spring.application.name=calendar
spring.config.import=optional:file:.env[.properties]@
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
server.servlet.context-path=/calendar
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.data.mongodb.auto-index-creation=false