spring:
  application:
    name: calendar

  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/dev

  data:
    mongodb:
      auto-index-creation: false

mongock:
  migration-scan-package:
    - com.pickme.calendar.infrastructure.migration.mongock
  enabled: true

server:
  servlet:
    context-path: /calendar

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}
      use-pkce-with-authorization-code-grant: true

logging:
  level:
    org.springframework.security: DEBUG
