spring:
  application:
    name: schedule

  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs

  data:
    mongodb:
      auto-index-creation: false

mongock:
  migration-scan-package:
    - com.pickme.schedule.infrastructure.migration.mongock
  enabled: true

server:
  servlet:
    context-path: /schedule

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      browser-access-url: http://${PUBLIC_BASE_DOMAIN}:${PUBLIC_BASE_PORT}/auth/realms/dev
      use-pkce-with-authorization-code-grant: true

logging:
  level:
    org.springframework.security: DEBUG
