spring.application.name=calendar
spring.config.import=optional:file:.env[.properties]@
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
springdoc.swagger-ui.path=/calendar/swagger-ui.html
springdoc.api-docs.path=/calendar/v3/api-docs
spring.data.mongodb.auto-index-creation=false